import pageStyle from './styles/TermsPage.css?raw'
import { usePageStyle } from '../hooks/usePageStyle'
import { useDocumentHead } from '../hooks/useDocumentHead'
import { Link } from 'react-router-dom'

export default function TermsPage() {
  usePageStyle(pageStyle)
  useDocumentHead({
    title: 'Terms of Service — Neurole',
    description: "The terms that apply to using Neurole's free neuroscience games and educational content.",
    canonical: '/terms',
  })

  return (
    <>
      <div className="page-hero"><div className="wrap">
      <Link className="back-home" to="/"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 12H5M12 19l-7-7 7-7" /></svg>Back to home</Link>
      <h1>Terms of Service</h1>
      <p className="legal-updated">Last updated: August 1, 2026</p>
      </div></div>
      
      <main className="wrap legal-body" style={{ padding: '36px 0 70px', maxWidth: '760px' }}>
      
        <p>These terms govern your use of Neurole (neurole.org). By using the site, you agree to them. If you don't agree, please don't use Neurole.</p>
      
        <div className="callout">
          <strong>Educational use only — not medical advice</strong>
          <p>Neurole's games, including The Daily Case, are for educational and entertainment purposes only. Nothing on this site is medical advice, and Neurole is not a substitute for professional medical judgment, diagnosis, or treatment. Case content is simplified for learning and should never be used to diagnose or treat yourself or anyone else. If you have a medical concern, consult a qualified healthcare professional.</p>
        </div>
      
        <h2>Who can use Neurole</h2>
        <p>Neurole is intended for general audiences, including students. If you are under the age of majority in your jurisdiction, you should have a parent or guardian's permission to use sites like this one, and to sign in with a Google account if you choose to.</p>
      
        <h2>AI-generated content</h2>
        <p>Neurole uses artificial intelligence (via a third-party AI provider) to power features like the "Explain" tutor and, on The Daily Case, automatically generated explanations of incorrect guesses. This means:</p>
        <ul>
          <li>Responses are generated by AI, not written or reviewed by a human before being shown to you.</li>
          <li>AI-generated content can be incomplete, oversimplified, or factually wrong. Treat it as a starting point for learning, not an authoritative source.</li>
          <li>You should independently verify anything important against a textbook, a qualified instructor, or another authoritative source.</li>
          <li>We do not use AI to make decisions about you, and no AI feature on this site provides medical, legal, or financial advice.</li>
        </ul>
      
        <h2>Educational content generally</h2>
        <p>Beyond AI-generated responses, case content, region data, and explanations on Neurole are written and reviewed on a volunteer basis. We aim for clinical accuracy but cannot guarantee it. If you spot an error, please tell us at <a href="mailto:neurolegames@gmail.com">neurolegames@gmail.com</a> — we rely on that.</p>
      
        <h2>Your account</h2>
        <p>Signing in is optional. If you sign in with Google, you're responsible for keeping that account secure. You can request that we delete your account data at any time.</p>
      
        <h2>Acceptable use</h2>
        <p>Please don't: attempt to disrupt or reverse-engineer the site in a harmful way; scrape or bulk-extract content for commercial use without permission; submit abusive, false, or harmful content through our forms; or use the site in any way that violates applicable law.</p>
      
        <h2>User-submitted content</h2>
        <p>If you submit a case, correction, or other content to Neurole (for example, through the "Create a Case" form), you grant us a non-exclusive, royalty-free license to use, edit, and publish it as part of the site. Don't submit anything you don't have the right to share.</p>
      
        <h2>Intellectual property</h2>
        <p>The Neurole name, logo, game design, and original content are owned by Neurole. Brain imagery and reference material used for educational purposes remain the property of their respective sources where applicable.</p>
      
        <h2>No warranty</h2>
        <p>Neurole is provided "as is" and "as available," without warranties of any kind, express or implied, including accuracy, availability, or fitness for a particular purpose. We're a small volunteer project — we do our best, but we can't guarantee the site will always be error-free, uninterrupted, or perfectly accurate.</p>
      
        <h2>Limitation of liability</h2>
        <p>To the fullest extent permitted by law, Neurole and its volunteers, contributors, and operators are not liable for any indirect, incidental, special, or consequential damages arising from your use of the site, including any decisions made based on its content. This does not limit liability where it cannot be limited under applicable law.</p>
      
        <h2>Indemnification</h2>
        <p>You agree to indemnify and hold Neurole and its volunteers harmless from any claims, damages, or expenses arising from your misuse of the site or violation of these terms.</p>
      
        <h2>Dispute resolution — arbitration agreement</h2>
        <p>Please read this section carefully. It affects your legal rights.</p>
        <p><strong>Agreement to arbitrate.</strong> You and Neurole agree that any dispute, claim, or controversy arising out of or relating to these Terms or your use of Neurole will be resolved through binding individual arbitration, rather than in court, except that either party may bring an individual claim in small claims court if it qualifies.</p>
        <p><strong>Class action waiver.</strong> You and Neurole agree that any arbitration or claim will be conducted only on an individual basis and not as a class, consolidated, or representative action.</p>
        <p><strong>How arbitration works.</strong> Arbitration will be administered by a recognized arbitration organization under its applicable rules, and will take place in a mutually reasonable location or, where available, remotely. The arbitrator's decision will be final and binding, subject to very limited court review.</p>
        <p><strong>30-day opt-out.</strong> You may opt out of this arbitration agreement by emailing <a href="mailto:neurolegames@gmail.com">neurolegames@gmail.com</a> with the subject line "Arbitration Opt-Out" within 30 days of first using Neurole, including your name and a statement that you wish to opt out. If you opt out, this arbitration section won't apply to you, but the rest of these Terms will.</p>
        <p><strong>Exceptions.</strong> Either party may seek injunctive or other equitable relief in court to prevent infringement or misuse of intellectual property.</p>
      
        <h2>Governing law</h2>
        <p>These terms are governed by the laws of the United States and the state in which Neurole is operated, without regard to conflict-of-law principles, except where applicable law requires otherwise.</p>
      
        <h2>Changes to these terms</h2>
        <p>We may update these terms from time to time. If we make material changes, we'll update the date at the top of this page. Continuing to use Neurole after a change means you accept the updated terms.</p>
      
        <h2>Contact</h2>
        <p>Questions about these terms: <a href="mailto:neurolegames@gmail.com">neurolegames@gmail.com</a>.</p>
      
        <p style={{ marginTop: '36px', paddingTop: '20px', borderTop: '1px solid var(--rule)', fontSize: '12.5px' }}>This page is a general template and is not legal advice. If you rely on the arbitration clause or need enforceability in a specific jurisdiction, have a licensed attorney review it — requirements for clear disclosure, opt-out mechanisms, and enforceability vary by state and country, and this section should not be treated as a final legal document without that review.</p>
      
      </main>
    </>
  )
}
